pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - master
      - develop
      - 'release/*'
      - 'hotfix/*'
      - 'feature/*'

  tags:
    include: [] 

steps:
- task: UseDotNet@2
  inputs:
    version: '2.1.818'
- task: UseDotNet@2
  inputs:
    version: '3.1.414'
- task: UseDotNet@2
  inputs:
    version: '5.0.402'
- task: UseDotNet@2
  inputs:
    version: '6.0.100-rc.2.21505.57'
    includePreviewVersions: true
- task: Cache@2
  inputs:
    key: '"$(Agent.OS)" | recipe.cake'
    path: 'tools'
- task: Cake@2
  inputs:
    script: 'recipe.cake'
    target: 'CI'
    verbosity: 'Diagnostic'
    Bootstrap: true
    Version: '0.38.5'
